### PR TITLE
Fix polling

### LINKED ISSUE #64: Polling timers can exhaust file descriptors
Gaba contains a number of classes that initiate a polling mechanism for querying remote services for
various information. Due to the way in which these timers are written, certain network conditions could
lead to “stacking” connections, thus causing an exhaustion of sockets/file descriptors.

### PR DESCRIPTION
**Pull request by brunobar79**
This PR fixes a couple of things:
- Replaces all `setInterval` ocurrences for recursive `setTimeout`
- Polling will wait for the last call to finish (or fail) before triggering a new one
- Prevent multiple calls to happen on init (`CurrencyController` and `TokenRatesController`) by disabling the controller until after init.

Fixes #64

### CODE REVIEW

File: src/ShapeShiftController.ts [hunk 1]
```diff
@@ -95,19 +95,21 @@ export class ShapeShiftController extends BaseController<ShapeShiftConfig, Shape
 		this.defaultConfig = { interval: 3000 };
 		this.defaultState = { shapeShiftTxList: [] };
 		this.initialize();
+		this.poll();
 	}
 
 	/**
-	 * Sets a new polling interval
+	 * starts a new polling interval
```
Comment (estebanmino) [inline src/ShapeShiftController.ts]: Very minor comment, we have documentation starting with capital letter, this (and other changes in the same method in other controllers) changes this

File: src/AssetsDetectionController.ts [hunk 2]
```diff
@@ -97,18 +97,21 @@ export class AssetsDetectionController extends BaseController<AssetsDetectionCon
...
 	 *
 	 * @param interval - Polling interval used to auto detect assets
 	 */
-	set interval(interval: number) {
-		this.handle && clearInterval(this.handle);
-		this.handle = setInterval(() => {
-			safelyExecute(() => this.detectAssets());
-		}, interval);
+	async poll(interval?: number) {
+		this.config.interval = interval || this.config.interval;
```
Comment (estebanmino) [inline src/AssetsDetectionController.ts]: is this working?  I believe you should call `this.configure()` to change the controller config (same applies to the other controller `poll` methods)

File: src/AssetsDetectionController.ts [hunk 3]
```diff
@@ -97,18 +97,21 @@ export class AssetsDetectionController extends BaseController<AssetsDetectionCon
...
+	 * starts a new polling interval
 	 *
 	 * @param interval - Polling interval used to auto detect assets
 	 */
-	set interval(interval: number) {
-		this.handle && clearInterval(this.handle);
-		this.handle = setInterval(() => {
-			safelyExecute(() => this.detectAssets());
-		}, interval);
+	async poll(interval?: number) {
```
Comment (estebanmino) [inline src/AssetsDetectionController.ts]: for documentation maybe `async poll(interval?: number): Promise<void>` would be nice to have (same for other controllers)
