### PR TITLE
bugfix: add address validation and improve safelyExecute

### LINKED ISSUE #65: Add validation to address book controller
The `AddressBookController` in Gaba does not perform any validation on the input and allows invalid
addresses.

### LINKED ISSUE #67: Preferences Controller should match against non-public IPs
There is a condition in the PreferencesController that checks if the RPC URL is
http://localhost:8545, presumably to check if the node is a local testing node. However, a user may
conceivably run their node on a different port, which would fail this check.

### LINKED ISSUE #70: The safelyExecute​Function Swallows Exceptions
Gaba often makes use of a utility function called safelyExecute. The purpose of this function is to call a supplied function without handling any exceptions or errors that may occur.

The safelyExecute function accepts a function that returns a Promise and then calls it inside of a try...catch block. The catch block does not handle exceptions, provide a way for the caller to handle them, or even log the error. Because of this failures and critical issues can go unnoticed.

### PR DESCRIPTION
**Pull request by bitpshr**
This pull request does the following:

- `safelyExecute` optionally logs errors and provides an optional retry logic path.
- The `AddressBookController` validates newly-added addresses.
- The `PreferencesController` loosely checks local RPC URLs (though this was technically unnecessary since we're checking against a constant string value [we set internally](https://github.com/MetaMask/gaba/blob/master/src/NetworkController.ts#L50).)

Fixes #65
Fixes #67
Fixes #70

### CODE REVIEW

File: src/AddressBookController.ts [hunk 1]
```diff
@@ -70,10 +72,15 @@ export class AddressBookController extends BaseController<BaseConfig, AddressBoo
 	 *
 	 * @param address - Recipient address to add or update
 	 * @param name - Nickname to associate with this address
+	 * @returns - Boolean indicating if the address was successfully set
 	 */
 	set(address: string, name: string) {
+		if (!isValidAddress(address)) {
+			return;
```
Comment (brunobar79) [inline src/AddressBookController.ts]: return false? (comment says it returns a boolean)

File: src/PreferencesController.ts [hunk 2]
```diff
@@ -31,6 +31,10 @@ export class PreferencesController extends BaseController<BaseConfig, Preference
 	 */
 	name = 'PreferencesController';
 
+	private isLocalURL(url: string) {
+		return /:\/\/localhost:/.test(url);
```
Comment (brunobar79) [inline src/PreferencesController.ts]: This fixe the port issue but the we should also be checking for any other non public IP like 127.0.0.1.

```
Mitigation: Simply match against 127.0.0.1, localhost, or any non-public IP address.
```

File: src/util.ts [hunk 3]
```diff
@@ -113,13 +113,16 @@ export function normalizeTransaction(transaction: Transaction) {
...
+ * @param retry - Function called if an error is caught
  * @returns - Promise resolving to the result of the async operation
  */
-export async function safelyExecute(operation: () => Promise<any>) {
+export async function safelyExecute(operation: () => Promise<any>, logError = false, retry?: (error: Error) => void) {
 	try {
 		return await operation();
 	} catch (error) {
-		/* tslint:disable-next-line:no-empty */
+		logError && console.error(error);
```
Comment (brunobar79) [inline src/util.ts]: 👏

File: src/PreferencesController.ts (hunk 2 above)
Comment (bitpshr) [reply src/PreferencesController.ts]: This suggestion from the audit was a little odd; AFAIK, there's no way to know how local hosts are configured on someone's machine. For example, I could locally resolve my local development node to `http://bitpshr.dev:1337` if I set up my host file accordingly. I guess checking readily-known local URLs is better than nothing.

Comment (brunobar79) [reply src/PreferencesController.ts]: I was talking about IPs not hosts.

Comment (bitpshr) [reply src/PreferencesController.ts]: I'm all for adding a cover-all regex for local IPs (candidly I did not know this was a matchable pattern, thanks for this) but as discussed offline, I worry a little about the usefulness of filtering out locally-hosted nodes.

Whether its a developer constantly hitting a local node during development, or a power user constantly hitting a local node for security, it feels like we should save these as "frequent", almost more-so than a public custom RPC network that may've been added by a user to test a one-off dapp.
